// flow-typed signature: a86e241c80e9625226303926a96f7536
// flow-typed version: <<STUB>>/compressing_v^1.4.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compressing'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compressing' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'compressing/lib/base_stream' {
  declare module.exports: any;
}

declare module 'compressing/lib/base_write_stream' {
  declare module.exports: any;
}

declare module 'compressing/lib/gzip/file_stream' {
  declare module.exports: any;
}

declare module 'compressing/lib/gzip' {
  declare module.exports: any;
}

declare module 'compressing/lib/gzip/uncompress_stream' {
  declare module.exports: any;
}

declare module 'compressing/lib/tar/file_stream' {
  declare module.exports: any;
}

declare module 'compressing/lib/tar' {
  declare module.exports: any;
}

declare module 'compressing/lib/tar/stream' {
  declare module.exports: any;
}

declare module 'compressing/lib/tar/uncompress_stream' {
  declare module.exports: any;
}

declare module 'compressing/lib/tgz/file_stream' {
  declare module.exports: any;
}

declare module 'compressing/lib/tgz' {
  declare module.exports: any;
}

declare module 'compressing/lib/tgz/stream' {
  declare module.exports: any;
}

declare module 'compressing/lib/tgz/uncompress_stream' {
  declare module.exports: any;
}

declare module 'compressing/lib/utils' {
  declare module.exports: any;
}

declare module 'compressing/lib/zip/file_stream' {
  declare module.exports: any;
}

declare module 'compressing/lib/zip' {
  declare module.exports: any;
}

declare module 'compressing/lib/zip/stream' {
  declare module.exports: any;
}

declare module 'compressing/lib/zip/uncompress_stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'compressing/index' {
  declare module.exports: $Exports<'compressing'>;
}
declare module 'compressing/index.js' {
  declare module.exports: $Exports<'compressing'>;
}
declare module 'compressing/lib/base_stream.js' {
  declare module.exports: $Exports<'compressing/lib/base_stream'>;
}
declare module 'compressing/lib/base_write_stream.js' {
  declare module.exports: $Exports<'compressing/lib/base_write_stream'>;
}
declare module 'compressing/lib/gzip/file_stream.js' {
  declare module.exports: $Exports<'compressing/lib/gzip/file_stream'>;
}
declare module 'compressing/lib/gzip/index' {
  declare module.exports: $Exports<'compressing/lib/gzip'>;
}
declare module 'compressing/lib/gzip/index.js' {
  declare module.exports: $Exports<'compressing/lib/gzip'>;
}
declare module 'compressing/lib/gzip/uncompress_stream.js' {
  declare module.exports: $Exports<'compressing/lib/gzip/uncompress_stream'>;
}
declare module 'compressing/lib/tar/file_stream.js' {
  declare module.exports: $Exports<'compressing/lib/tar/file_stream'>;
}
declare module 'compressing/lib/tar/index' {
  declare module.exports: $Exports<'compressing/lib/tar'>;
}
declare module 'compressing/lib/tar/index.js' {
  declare module.exports: $Exports<'compressing/lib/tar'>;
}
declare module 'compressing/lib/tar/stream.js' {
  declare module.exports: $Exports<'compressing/lib/tar/stream'>;
}
declare module 'compressing/lib/tar/uncompress_stream.js' {
  declare module.exports: $Exports<'compressing/lib/tar/uncompress_stream'>;
}
declare module 'compressing/lib/tgz/file_stream.js' {
  declare module.exports: $Exports<'compressing/lib/tgz/file_stream'>;
}
declare module 'compressing/lib/tgz/index' {
  declare module.exports: $Exports<'compressing/lib/tgz'>;
}
declare module 'compressing/lib/tgz/index.js' {
  declare module.exports: $Exports<'compressing/lib/tgz'>;
}
declare module 'compressing/lib/tgz/stream.js' {
  declare module.exports: $Exports<'compressing/lib/tgz/stream'>;
}
declare module 'compressing/lib/tgz/uncompress_stream.js' {
  declare module.exports: $Exports<'compressing/lib/tgz/uncompress_stream'>;
}
declare module 'compressing/lib/utils.js' {
  declare module.exports: $Exports<'compressing/lib/utils'>;
}
declare module 'compressing/lib/zip/file_stream.js' {
  declare module.exports: $Exports<'compressing/lib/zip/file_stream'>;
}
declare module 'compressing/lib/zip/index' {
  declare module.exports: $Exports<'compressing/lib/zip'>;
}
declare module 'compressing/lib/zip/index.js' {
  declare module.exports: $Exports<'compressing/lib/zip'>;
}
declare module 'compressing/lib/zip/stream.js' {
  declare module.exports: $Exports<'compressing/lib/zip/stream'>;
}
declare module 'compressing/lib/zip/uncompress_stream.js' {
  declare module.exports: $Exports<'compressing/lib/zip/uncompress_stream'>;
}
