// flow-typed signature: d2592419576d1fe7f3971c61983732be
// flow-typed version: <<STUB>>/css-vars_v^2.2.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'css-vars'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'css-vars' {
  declare module.exports: any;
}
