// flow-typed signature: 51c5d4c9f3db68f1e83a391b79309c3c
// flow-typed version: <<STUB>>/discord-rpc_v^3.0.2/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'discord-rpc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'discord-rpc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'discord-rpc/browser' {
  declare module.exports: any;
}

declare module 'discord-rpc/src/client' {
  declare module.exports: any;
}

declare module 'discord-rpc/src/constants' {
  declare module.exports: any;
}

declare module 'discord-rpc/src' {
  declare module.exports: any;
}

declare module 'discord-rpc/src/transports' {
  declare module.exports: any;
}

declare module 'discord-rpc/src/transports/ipc' {
  declare module.exports: any;
}

declare module 'discord-rpc/src/transports/websocket' {
  declare module.exports: any;
}

declare module 'discord-rpc/src/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'discord-rpc/browser.js' {
  declare module.exports: $Exports<'discord-rpc/browser'>;
}
declare module 'discord-rpc/src/client.js' {
  declare module.exports: $Exports<'discord-rpc/src/client'>;
}
declare module 'discord-rpc/src/constants.js' {
  declare module.exports: $Exports<'discord-rpc/src/constants'>;
}
declare module 'discord-rpc/src/index' {
  declare module.exports: $Exports<'discord-rpc/src'>;
}
declare module 'discord-rpc/src/index.js' {
  declare module.exports: $Exports<'discord-rpc/src'>;
}
declare module 'discord-rpc/src/transports/index' {
  declare module.exports: $Exports<'discord-rpc/src/transports'>;
}
declare module 'discord-rpc/src/transports/index.js' {
  declare module.exports: $Exports<'discord-rpc/src/transports'>;
}
declare module 'discord-rpc/src/transports/ipc.js' {
  declare module.exports: $Exports<'discord-rpc/src/transports/ipc'>;
}
declare module 'discord-rpc/src/transports/websocket.js' {
  declare module.exports: $Exports<'discord-rpc/src/transports/websocket'>;
}
declare module 'discord-rpc/src/util.js' {
  declare module.exports: $Exports<'discord-rpc/src/util'>;
}
