// flow-typed signature: 2e471872ea160d47708d0ff1a5a94cab
// flow-typed version: <<STUB>>/jarfile_v^2.0.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jarfile'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jarfile' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jarfile/src/Jar' {
  declare module.exports: any;
}

declare module 'jarfile/test/Jar_test' {
  declare module.exports: any;
}

declare module 'jarfile/test/smoke' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jarfile/index' {
  declare module.exports: $Exports<'jarfile'>;
}
declare module 'jarfile/index.js' {
  declare module.exports: $Exports<'jarfile'>;
}
declare module 'jarfile/src/Jar.js' {
  declare module.exports: $Exports<'jarfile/src/Jar'>;
}
declare module 'jarfile/test/Jar_test.js' {
  declare module.exports: $Exports<'jarfile/test/Jar_test'>;
}
declare module 'jarfile/test/smoke.js' {
  declare module.exports: $Exports<'jarfile/test/smoke'>;
}
