// flow-typed signature: 51b84de360240b076fa9008a92744f7c
// flow-typed version: <<STUB>>/murmurhash-js_v^1.0.0/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'murmurhash-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'murmurhash-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'murmurhash-js/murmurhash2_gc' {
  declare module.exports: any;
}

declare module 'murmurhash-js/murmurhash3_gc' {
  declare module.exports: any;
}

// Filename aliases
declare module 'murmurhash-js/index' {
  declare module.exports: $Exports<'murmurhash-js'>;
}
declare module 'murmurhash-js/index.js' {
  declare module.exports: $Exports<'murmurhash-js'>;
}
declare module 'murmurhash-js/murmurhash2_gc.js' {
  declare module.exports: $Exports<'murmurhash-js/murmurhash2_gc'>;
}
declare module 'murmurhash-js/murmurhash3_gc.js' {
  declare module.exports: $Exports<'murmurhash-js/murmurhash3_gc'>;
}
