// flow-typed signature: ca8bd48e49af4d68eabda27a69054596
// flow-typed version: <<STUB>>/universal-analytics_v^0.4.20/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'universal-analytics'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'universal-analytics' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'universal-analytics/lib/config' {
  declare module.exports: any;
}

declare module 'universal-analytics/lib' {
  declare module.exports: any;
}

declare module 'universal-analytics/lib/utils' {
  declare module.exports: any;
}

declare module 'universal-analytics/test/_enqueue' {
  declare module.exports: any;
}

declare module 'universal-analytics/test/event' {
  declare module.exports: any;
}

declare module 'universal-analytics/test/exception' {
  declare module.exports: any;
}

declare module 'universal-analytics/test' {
  declare module.exports: any;
}

declare module 'universal-analytics/test/item' {
  declare module.exports: any;
}

declare module 'universal-analytics/test/middleware' {
  declare module.exports: any;
}

declare module 'universal-analytics/test/pageview' {
  declare module.exports: any;
}

declare module 'universal-analytics/test/send' {
  declare module.exports: any;
}

declare module 'universal-analytics/test/set' {
  declare module.exports: any;
}

declare module 'universal-analytics/test/timing' {
  declare module.exports: any;
}

declare module 'universal-analytics/test/transaction' {
  declare module.exports: any;
}

// Filename aliases
declare module 'universal-analytics/index' {
  declare module.exports: $Exports<'universal-analytics'>;
}
declare module 'universal-analytics/index.js' {
  declare module.exports: $Exports<'universal-analytics'>;
}
declare module 'universal-analytics/lib/config.js' {
  declare module.exports: $Exports<'universal-analytics/lib/config'>;
}
declare module 'universal-analytics/lib/index' {
  declare module.exports: $Exports<'universal-analytics/lib'>;
}
declare module 'universal-analytics/lib/index.js' {
  declare module.exports: $Exports<'universal-analytics/lib'>;
}
declare module 'universal-analytics/lib/utils.js' {
  declare module.exports: $Exports<'universal-analytics/lib/utils'>;
}
declare module 'universal-analytics/test/_enqueue.js' {
  declare module.exports: $Exports<'universal-analytics/test/_enqueue'>;
}
declare module 'universal-analytics/test/event.js' {
  declare module.exports: $Exports<'universal-analytics/test/event'>;
}
declare module 'universal-analytics/test/exception.js' {
  declare module.exports: $Exports<'universal-analytics/test/exception'>;
}
declare module 'universal-analytics/test/index' {
  declare module.exports: $Exports<'universal-analytics/test'>;
}
declare module 'universal-analytics/test/index.js' {
  declare module.exports: $Exports<'universal-analytics/test'>;
}
declare module 'universal-analytics/test/item.js' {
  declare module.exports: $Exports<'universal-analytics/test/item'>;
}
declare module 'universal-analytics/test/middleware.js' {
  declare module.exports: $Exports<'universal-analytics/test/middleware'>;
}
declare module 'universal-analytics/test/pageview.js' {
  declare module.exports: $Exports<'universal-analytics/test/pageview'>;
}
declare module 'universal-analytics/test/send.js' {
  declare module.exports: $Exports<'universal-analytics/test/send'>;
}
declare module 'universal-analytics/test/set.js' {
  declare module.exports: $Exports<'universal-analytics/test/set'>;
}
declare module 'universal-analytics/test/timing.js' {
  declare module.exports: $Exports<'universal-analytics/test/timing'>;
}
declare module 'universal-analytics/test/transaction.js' {
  declare module.exports: $Exports<'universal-analytics/test/transaction'>;
}
