// flow-typed signature: 91443d5882205f75bb7f740395a2ce3f
// flow-typed version: <<STUB>>/version-sort_v^0.1.1/flow_v0.106.3

/**
 * This is an autogenerated libdef stub for:
 *
 *   'version-sort'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'version-sort' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'version-sort/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'version-sort/index' {
  declare module.exports: $Exports<'version-sort'>;
}
declare module 'version-sort/index.js' {
  declare module.exports: $Exports<'version-sort'>;
}
declare module 'version-sort/test/index' {
  declare module.exports: $Exports<'version-sort/test'>;
}
declare module 'version-sort/test/index.js' {
  declare module.exports: $Exports<'version-sort/test'>;
}
